name: cd-dev-wf
on: 
  push:
    branches:
      - develop
jobs:
  deploy-dev-job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: deploy website
        run: curl -X POST ${{ secrets.DEVELOP_ENV_HOOK}} 