name: cd-stage-wf
on: 
  push:
    branches:
      - release
jobs:
  deploy-staging-job:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy Website
        run: curl -X POST ${{ secrets.STAGING_ENV_HOOK}}